# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('braindump', '0002_split_card_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardplacement',
            options={'ordering': ['area']},
        ),
    ]
