# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('braindump', '0003_auto_20180411_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardplacement',
            name='postpone_until',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
