# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braindump', '0004_fix_postpone_until_default'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cardplacement',
            index=models.Index(fields=['user'], name='braindump_c_user_id_4ce371_idx'),
        ),
        migrations.AddIndex(
            model_name='cardplacement',
            index=models.Index(fields=['card'], name='braindump_c_card_id_efea88_idx'),
        ),
    ]
