# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170925_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Strict'), (2, 'Defensive')], default=1),
        ),
    ]
