# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0009_sharecontract'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharecontract',
            unique_together=set([('category', 'user')]),
        ),
    ]
