# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_auto_20180411_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='last_interaction',
        ),
    ]
