# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-03 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userguisettings',
            options={'verbose_name_plural': 'user gui settings'},
        ),
    ]
