# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-03 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20181203_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userguisettings',
            options={'verbose_name': 'User GUI settings', 'verbose_name_plural': 'User GUI settings'},
        ),
    ]
