# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='area',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='hint',
            field=models.TextField(blank=True),
        ),
    ]
