# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20170924_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='area',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1),
        ),
    ]
