# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20170924_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['area']},
        ),
    ]
