# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20170925_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['_area']},
        ),
        migrations.RenameField(
            model_name='card',
            old_name='area',
            new_name='_area',
        ),
    ]
