# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20171213_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.TextField(verbose_name='Answer (Markdown)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='hint',
            field=models.TextField(blank=True, verbose_name='Hint (Markdown)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.TextField(verbose_name='Question (Markdown)'),
        ),
    ]
