# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_card_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='categories.Category'),
        ),
    ]
