# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20180319_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='card',
            name='hint',
            field=models.TextField(blank=True, verbose_name='Hint'),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
