# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20180331_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='postpone_until',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
