# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_card_postpone_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.RemoveField(
            model_name='card',
            name='area',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_interaction',
        ),
        migrations.RemoveField(
            model_name='card',
            name='postpone_until',
        ),
    ]
